steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/clasp', './clasp' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/firebase', './firebase' ]
images:
  - 'gcr.io/$PROJECT_ID/clasp'
  - 'gcr.io/$PROJECT_ID/firebase'